[build]
  publish = "."

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-store, max-age=0"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store, max-age=0"

[[headers]]
  for = "/install.sh"
  [headers.values]
    Cache-Control = "no-store, max-age=0"
